language: objective-c
osx_image: xcode7.3
script: set -o pipefail && xcodebuild test -destination platform="iOS Simulator,name=iPhone 6s,OS=9.3" -workspace IOSSwiftBoiler.xcworkspace -scheme IOSSwiftBoiler -sdk iphonesimulator9.3 | xcpretty