matrix:
  include:
    - os: osx
      language: objective-c
      xcode_workspace: IOSSwiftBoiler.xcworkspace
      xcode_scheme: IOSSwiftBoiler
      xcode_sdk: iphonesimulator9.3
      script: xcodebuild test -destination platform="iOS Simulator,name=iPhone 6s,OS=9.2" -scheme IOSSwiftBoiler
      osx_image: xcode7.3
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install -y clang libicu-dev
        - ./install-linux-swift.sh
        - export PATH="/swift/usr/bin:${PATH}"
 	- pod install
      script:
        - swift build -v
        - swift test
