matrix:
  include:
    - os: osx
      langnguage: objective-c
      xcode_workspace: IOSSwiftBoiler.xcworkspace
      xcode_scheme: IOSSwiftBoiler
      xcode_sdk: iphonesimulator9.3
      script: xcodebuild -scheme IOSSwiftBoiler test
      osx_image: xcode7.3
    - os: osx
      language: objective-c # this is a lie
      xcode_workspace: IOSSwiftBoiler.xcworkspace
      xcode_scheme: IOSSwiftBoiler
      xcode_sdk: iphonesimulator9.3
      script: xcodebuild -destination platform="iOS Simulator,name=iPhone 6,OS=9.3" -scheme IOSSwiftBoiler test
      osx_image: xcode7.2
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install -y clang libicu-dev
        - ./install-linux-swift.sh
        - export PATH="/swift/usr/bin:${PATH}"
      script:
        - swift build -v
        - swift test